// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-redesign/PrestigeNoir.tsx": () => import("../components/mockups/dashboard-redesign/PrestigeNoir.tsx"),
  "./components/mockups/dashboard-redesign/SapphirePro.tsx": () => import("../components/mockups/dashboard-redesign/SapphirePro.tsx"),
  "./components/mockups/dashboard-redesign/SlateEmerald.tsx": () => import("../components/mockups/dashboard-redesign/SlateEmerald.tsx")
};
